CC = gcc
CP = python3
LIBS = -lgsl -lgslcblas -lm

master:Main.c
	$(CC) -o main.o Main.c $(LIBS)
	./main.o

	@echo ""
	@echo "<-------------------------	.THE END.	------------------------->"
	@echo ""


